package ontology

// OvaholNameRefinementRules holds the legacy Ovahol name refinements as structured data.
var OvaholNameRefinementRules = []NameRefinementRule{
	{TargetName: "Thermometer", Keywords: []string{"non contact", "non-contact", "infrared"}, CommonName: "Infrared thermometer", CanonicalName: ""},
	{TargetName: "Thermometer", Keywords: []string{"tympanic", "ear"}, CommonName: "Ear thermometer", CanonicalName: ""},
	{TargetName: "Thermometer", Keywords: []string{"digital"}, CommonName: "Digital thermometer", CanonicalName: ""},
	{TargetName: "Thermometer", Keywords: []string{"laboratory", "glass"}, CommonName: "Laboratory thermometer", CanonicalName: ""},
	{TargetName: "Thermometer", Keywords: []string{"water bath"}, CommonName: "Water bath thermometer", CanonicalName: ""},
	{TargetName: "Thermometer", Keywords: []string{"calibrated"}, CommonName: "Calibrated thermometer", CanonicalName: ""},
	{TargetName: "Thermometer", Keywords: []string{}, CommonName: "Clinical thermometer", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"stadiometer", "altimeter", "height"}, CommonName: "Height and weight scale", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"blood bag", "donor blood", "blood scales"}, CommonName: "Blood bag scale", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"neonatal", "infant"}, CommonName: "Neonatal scale", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"analytical"}, CommonName: "Analytical balance", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"technical"}, CommonName: "Technical balance", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"precision"}, CommonName: "Precision balance", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"spring"}, CommonName: "Spring scale", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"hanging"}, CommonName: "Hanging scale", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"wheelchair"}, CommonName: "Wheelchair scale", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"bariatric"}, CommonName: "Bariatric scale", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"bed"}, CommonName: "Bed scale", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"chair"}, CommonName: "Chair scale", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"standing", "column"}, CommonName: "Column scale", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"bathroom", "floor"}, CommonName: "Floor scale", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"kitchen"}, CommonName: "Kitchen scale", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"baby", "infant", "child"}, CommonName: "Baby scale", CanonicalName: ""},
	{TargetName: "Scale", Keywords: []string{"adult"}, CommonName: "Adult scale", CanonicalName: ""},
	{TargetName: "Pipette", Keywords: []string{"multichannel"}, CommonName: "Multichannel pipette", CanonicalName: ""},
	{TargetName: "Pipette", Keywords: []string{"electronic"}, CommonName: "Electronic pipette", CanonicalName: ""},
	{TargetName: "Pipette", Keywords: []string{"repeater", "repeating"}, CommonName: "Repeater pipette", CanonicalName: ""},
	{TargetName: "Pipette", Keywords: []string{"pasteur"}, CommonName: "Pasteur pipette", CanonicalName: ""},
	{TargetName: "Pipette", Keywords: []string{"serological"}, CommonName: "Serological pipette", CanonicalName: ""},
	{TargetName: "Pipette", Keywords: []string{"measuring"}, CommonName: "Measuring pipette", CanonicalName: ""},
	{TargetName: "Pipette", Keywords: []string{"volumetric"}, CommonName: "Volumetric pipette", CanonicalName: ""},
	{TargetName: "Pipette", Keywords: []string{"transfer"}, CommonName: "Transfer pipette", CanonicalName: ""},
	{TargetName: "Pipette", Keywords: []string{"micro"}, CommonName: "Micropipette", CanonicalName: ""},
	{TargetName: "Pipette", Keywords: []string{}, CommonName: "Pipette", CanonicalName: ""},
	{TargetName: "Lamp", Keywords: []string{"slit"}, CommonName: "Slit lamp", CanonicalName: "Ophthalmic slit lamp"},
	{TargetName: "Lamp", Keywords: []string{"phototherapy"}, CommonName: "Phototherapy lamp", CanonicalName: "Neonatal phototherapy lamp"},
	{TargetName: "Lamp", Keywords: []string{"wood", "woods"}, CommonName: "Wood lamp", CanonicalName: "Dermatological wood lamp"},
	{TargetName: "Lamp", Keywords: []string{"infrared"}, CommonName: "Infrared lamp", CanonicalName: "Infrared heating lamp"},
	{TargetName: "Lamp", Keywords: []string{"examination", "exam"}, CommonName: "Examination lamp", CanonicalName: "Clinical examination light"},
	{TargetName: "Lamp", Keywords: []string{"surgical", "theatre", "operating"}, CommonName: "Surgical lamp", CanonicalName: "Surgical light"},
	{TargetName: "Ventilator", Keywords: []string{"transport", "portable"}, CommonName: "Transport ventilator", CanonicalName: "Emergency transport ventilator"},
	{TargetName: "Ventilator", Keywords: []string{"neonatal", "infant"}, CommonName: "Neonatal ventilator", CanonicalName: "Neonatal intensive care ventilator"},
	{TargetName: "Ventilator", Keywords: []string{"intensive care", "icu"}, CommonName: "ICU ventilator", CanonicalName: "Critical care ventilator"},
	{TargetName: "Ventilator", Keywords: []string{"non-invasive", "non invasive", "niv"}, CommonName: "Non-invasive ventilator", CanonicalName: "Non-invasive positive pressure ventilator"},
	{TargetName: "Ventilator", Keywords: []string{}, CommonName: "Ventilator", CanonicalName: "Mechanical ventilator"},
	{TargetName: "Ultrasound scanner", Keywords: []string{"echocardiography", "cardiac"}, CommonName: "Cardiac ultrasound scanner", CanonicalName: "Echocardiography system"},
	{TargetName: "Ultrasound scanner", Keywords: []string{"vascular"}, CommonName: "Vascular ultrasound scanner", CanonicalName: "Vascular ultrasound imaging system"},
	{TargetName: "Ultrasound scanner", Keywords: []string{"portable", "handheld", "point of care", "poc"}, CommonName: "Portable ultrasound scanner", CanonicalName: "Portable diagnostic ultrasound system"},
	{TargetName: "Ultrasound scanner", Keywords: []string{"ophthalmic"}, CommonName: "Ophthalmic ultrasound scanner", CanonicalName: "Ophthalmic ultrasound system"},
	{TargetName: "Ultrasound scanner", Keywords: []string{}, CommonName: "Ultrasound scanner", CanonicalName: "Diagnostic ultrasound system"},
	{TargetName: "Oxygen flowmeter", Keywords: []string{"thorpe tube", "pipeline"}, CommonName: "Oxygen flowmeter", CanonicalName: "Medical oxygen flowmeter"},
	{TargetName: "Microscope", Keywords: []string{"operating", "surgical"}, CommonName: "Surgical microscope", CanonicalName: "Operating microscope"},
	{TargetName: "Microscope", Keywords: []string{"fluorescence"}, CommonName: "Fluorescence microscope", CanonicalName: "Laboratory fluorescence microscope"},
	{TargetName: "Microscope", Keywords: []string{"inverted"}, CommonName: "Inverted microscope", CanonicalName: "Laboratory inverted microscope"},
	{TargetName: "Microscope", Keywords: []string{"phase contrast"}, CommonName: "Phase contrast microscope", CanonicalName: "Phase contrast microscope"},
	{TargetName: "Microscope", Keywords: []string{"stereo", "stereoscopic"}, CommonName: "Stereomicroscope", CanonicalName: "Laboratory stereomicroscope"},
	{TargetName: "Microscope", Keywords: []string{"electron"}, CommonName: "Electron microscope", CanonicalName: "Transmission or scanning electron microscope"},
	{TargetName: "Microscope", Keywords: []string{"darkfield"}, CommonName: "Darkfield microscope", CanonicalName: "Laboratory darkfield microscope"},
	{TargetName: "Microscope", Keywords: []string{"polarizing"}, CommonName: "Polarizing microscope", CanonicalName: "Laboratory polarizing microscope"},
	{TargetName: "Microscope", Keywords: []string{"binocular"}, CommonName: "Binocular microscope", CanonicalName: "Laboratory binocular microscope"},
	{TargetName: "Microscope", Keywords: []string{"monocular"}, CommonName: "Monocular microscope", CanonicalName: "Laboratory monocular microscope"},
	{TargetName: "Microscope", Keywords: []string{"trinocular"}, CommonName: "Trinocular microscope", CanonicalName: "Laboratory trinocular microscope"},
	{TargetName: "Microscope", Keywords: []string{}, CommonName: "Laboratory microscope", CanonicalName: "Clinical laboratory microscope"},
	{TargetName: "Refrigerator", Keywords: []string{"blood bank"}, CommonName: "Blood bank refrigerator", CanonicalName: "Blood storage refrigerator"},
	{TargetName: "Refrigerator", Keywords: []string{"vaccine", "cold chain"}, CommonName: "Vaccine refrigerator", CanonicalName: "Solar or electric vaccine refrigerator"},
	{TargetName: "Refrigerator", Keywords: []string{"pharmacy"}, CommonName: "Pharmacy refrigerator", CanonicalName: "Pharmaceutical storage refrigerator"},
	{TargetName: "Refrigerator", Keywords: []string{"morgue", "mortuary"}, CommonName: "Mortuary refrigerator", CanonicalName: "Mortuary cadaver refrigerator"},
	{TargetName: "Refrigerator", Keywords: []string{"explosion proof"}, CommonName: "Explosion-proof refrigerator", CanonicalName: "Explosion-proof laboratory refrigerator"},
	{TargetName: "Refrigerator", Keywords: []string{}, CommonName: "Laboratory refrigerator", CanonicalName: "Standard laboratory refrigerator"},
	{TargetName: "Centrifuge", Keywords: []string{"microhaematocrit", "microhematocrit"}, CommonName: "Microhematocrit centrifuge", CanonicalName: "Microhematocrit centrifuge"},
	{TargetName: "Centrifuge", Keywords: []string{"refrigerated"}, CommonName: "Refrigerated centrifuge", CanonicalName: "Refrigerated laboratory centrifuge"},
	{TargetName: "Centrifuge", Keywords: []string{"blood bank", "cell washer"}, CommonName: "Blood bank centrifuge", CanonicalName: "Blood bank or cell washing centrifuge"},
	{TargetName: "Centrifuge", Keywords: []string{"ultracentrifuge"}, CommonName: "Ultracentrifuge", CanonicalName: "High-speed ultracentrifuge"},
	{TargetName: "Centrifuge", Keywords: []string{"microcentrifuge"}, CommonName: "Microcentrifuge", CanonicalName: "Benchtop microcentrifuge"},
	{TargetName: "Centrifuge", Keywords: []string{"clinical", "benchtop"}, CommonName: "Benchtop clinical centrifuge", CanonicalName: "Clinical benchtop centrifuge"},
	{TargetName: "Centrifuge", Keywords: []string{}, CommonName: "Laboratory centrifuge", CanonicalName: "General laboratory centrifuge"},
	{TargetName: "Laser", Keywords: []string{"nd yag", "yag"}, CommonName: "Nd:YAG laser", CanonicalName: "Nd:YAG surgical or ophthalmic laser"},
	{TargetName: "Laser", Keywords: []string{"argon"}, CommonName: "Argon laser", CanonicalName: "Argon laser system"},
	{TargetName: "Laser", Keywords: []string{"co2", "carbon dioxide"}, CommonName: "CO2 laser", CanonicalName: "Surgical CO2 laser system"},
	{TargetName: "Laser", Keywords: []string{"diode"}, CommonName: "Diode laser", CanonicalName: "Medical diode laser system"},
	{TargetName: "Laser", Keywords: []string{"excimer"}, CommonName: "Excimer laser", CanonicalName: "Refractive excimer laser system"},
	{TargetName: "Laser", Keywords: []string{"holmium"}, CommonName: "Holmium laser", CanonicalName: "Holmium surgical laser"},
	{TargetName: "Laser", Keywords: []string{}, CommonName: "Medical laser", CanonicalName: "Medical or surgical laser system"},
	{TargetName: "Cart", Keywords: []string{"emergency", "crash", "resuscitation"}, CommonName: "Crash cart", CanonicalName: "Emergency resuscitation crash cart"},
	{TargetName: "Cart", Keywords: []string{"anesthesia", "anaesthesia"}, CommonName: "Anesthesia cart", CanonicalName: "Anesthesia procedure cart"},
	{TargetName: "Cart", Keywords: []string{"medication", "dose"}, CommonName: "Medication cart", CanonicalName: "Medication dispensing cart"},
	{TargetName: "Cart", Keywords: []string{"isolation"}, CommonName: "Isolation cart", CanonicalName: "Infection control isolation cart"},
	{TargetName: "Cart", Keywords: []string{"treatment", "procedure"}, CommonName: "Procedure cart", CanonicalName: "Clinical procedure cart"},
	{TargetName: "Cart", Keywords: []string{}, CommonName: "Medical utility cart", CanonicalName: "Hospital utility transport cart"},
	{TargetName: "Trolley", Keywords: []string{"dressing"}, CommonName: "Dressing trolley", CanonicalName: "Clinical dressing trolley"},
	{TargetName: "Trolley", Keywords: []string{"instrument"}, CommonName: "Instrument trolley", CanonicalName: "Surgical instrument trolley"},
	{TargetName: "Trolley", Keywords: []string{"patient", "transport"}, CommonName: "Patient trolley", CanonicalName: "Patient transport trolley"},
	{TargetName: "Trolley", Keywords: []string{}, CommonName: "Medical trolley", CanonicalName: "Hospital utility trolley"},
	{TargetName: "Bath", Keywords: []string{"water"}, CommonName: "Water bath", CanonicalName: "Laboratory water bath"},
	{TargetName: "Bath", Keywords: []string{"histology", "tissue flotation"}, CommonName: "Tissue flotation bath", CanonicalName: "Histology tissue flotation bath"},
	{TargetName: "Bath", Keywords: []string{"paraffin", "wax"}, CommonName: "Paraffin wax bath", CanonicalName: "Paraffin wax dispenser bath"},
	{TargetName: "Bath", Keywords: []string{"ultrasonic"}, CommonName: "Ultrasonic cleaning bath", CanonicalName: "Ultrasonic instrument cleaning bath"},
	{TargetName: "Bath", Keywords: []string{}, CommonName: "Laboratory bath", CanonicalName: "Temperature controlled laboratory bath"},
	{TargetName: "Bed", Keywords: []string{"icu", "intensive care"}, CommonName: "ICU bed", CanonicalName: "Intensive care hospital bed"},
	{TargetName: "Bed", Keywords: []string{"birthing", "delivery"}, CommonName: "Birthing bed", CanonicalName: "Obstetric delivery bed"},
	{TargetName: "Bed", Keywords: []string{"electric"}, CommonName: "Electric hospital bed", CanonicalName: "Electrically powered hospital bed"},
	{TargetName: "Bed", Keywords: []string{"manual", "mechanical"}, CommonName: "Manual hospital bed", CanonicalName: "Manually adjustable hospital bed"},
	{TargetName: "Bed", Keywords: []string{"orthopaedic", "orthopedic"}, CommonName: "Orthopedic bed", CanonicalName: "Orthopedic traction bed"},
	{TargetName: "Bed", Keywords: []string{"paediatric", "pediatric"}, CommonName: "Pediatric bed", CanonicalName: "Pediatric hospital bed"},
	{TargetName: "Bed", Keywords: []string{}, CommonName: "Hospital bed", CanonicalName: "Standard patient hospital bed"},
	{TargetName: "Calliper", Keywords: []string{"skin fold", "skinfold"}, CommonName: "Skinfold caliper", CanonicalName: "Skinfold body fat caliper"},
	{TargetName: "Calliper", Keywords: []string{}, CommonName: "Medical caliper", CanonicalName: "Diagnostic measuring caliper"},
	{TargetName: "Fetal monitor", Keywords: []string{"doppler", "ultrasound"}, CommonName: "Fetal Doppler", CanonicalName: "Handheld Doppler fetal monitor"},
	{TargetName: "Fetal monitor", Keywords: []string{"cardiotocograph", "ctg"}, CommonName: "Cardiotocograph", CanonicalName: "Fetal cardiotocograph monitor"},
	{TargetName: "Fetal monitor", Keywords: []string{}, CommonName: "Fetal monitor", CanonicalName: "Electronic fetal heart rate monitor"},
	{TargetName: "Oven", Keywords: []string{"drying"}, CommonName: "Laboratory drying oven", CanonicalName: "Laboratory drying and heating oven"},
	{TargetName: "Oven", Keywords: []string{"hybridization"}, CommonName: "Hybridization oven", CanonicalName: "Molecular hybridization oven"},
	{TargetName: "Oven", Keywords: []string{"sterilizing", "hot air"}, CommonName: "Hot air sterilizer oven", CanonicalName: "Hot air sterilizing dry oven"},
	{TargetName: "Oven", Keywords: []string{}, CommonName: "Laboratory oven", CanonicalName: "General laboratory heating oven"},
	{TargetName: "Stretcher", Keywords: []string{"ambulance"}, CommonName: "Ambulance stretcher", CanonicalName: "Roll-in ambulance stretcher"},
	{TargetName: "Stretcher", Keywords: []string{"scoop"}, CommonName: "Scoop stretcher", CanonicalName: "Orthopedic scoop stretcher"},
	{TargetName: "Stretcher", Keywords: []string{"basket"}, CommonName: "Basket stretcher", CanonicalName: "Emergency rescue basket stretcher"},
	{TargetName: "Stretcher", Keywords: []string{"folding", "foldable"}, CommonName: "Folding stretcher", CanonicalName: "Portable folding emergency stretcher"},
	{TargetName: "Stretcher", Keywords: []string{"spine board", "backboard"}, CommonName: "Spine board", CanonicalName: "Rigid emergency spine board"},
	{TargetName: "Stretcher", Keywords: []string{}, CommonName: "Patient stretcher", CanonicalName: "Emergency transport patient stretcher"},
	{TargetName: "Warmer", Keywords: []string{"infant", "radiant"}, CommonName: "Infant radiant warmer", CanonicalName: "Neonatal radiant warmer"},
	{TargetName: "Warmer", Keywords: []string{"blood", "fluid"}, CommonName: "Blood and fluid warmer", CanonicalName: "Intravenous blood and fluid warming system"},
	{TargetName: "Warmer", Keywords: []string{"blanket", "patient"}, CommonName: "Patient warming system", CanonicalName: "Forced-air patient warming unit"},
	{TargetName: "Warmer", Keywords: []string{}, CommonName: "Medical warmer", CanonicalName: "Clinical thermal warming device"},
	{TargetName: "Chemistry analyzer", Keywords: []string{"automated", "automatic"}, CommonName: "Automated chemistry analyzer", CanonicalName: "Automated clinical chemistry analyzer"},
	{TargetName: "Chemistry analyzer", Keywords: []string{"semi-automated", "semi automated"}, CommonName: "Semi-automated chemistry analyzer", CanonicalName: "Semi-automated clinical chemistry analyzer"},
	{TargetName: "Chemistry analyzer", Keywords: []string{"dry", "point of care"}, CommonName: "Point-of-care chemistry analyzer", CanonicalName: "Dry chemistry point-of-care analyzer"},
	{TargetName: "Chemistry analyzer", Keywords: []string{}, CommonName: "Chemistry analyzer", CanonicalName: "Clinical chemistry analyzer"},
	{TargetName: "Laboratory bath", Keywords: []string{"water"}, CommonName: "Water bath", CanonicalName: "Laboratory water bath"},
	{TargetName: "Laboratory bath", Keywords: []string{"shaking"}, CommonName: "Shaking water bath", CanonicalName: "Reciprocal shaking water bath"},
	{TargetName: "Laboratory bath", Keywords: []string{}, CommonName: "Laboratory bath", CanonicalName: "Laboratory liquid bath"},
	{TargetName: "Biometer", Keywords: []string{"optical"}, CommonName: "Optical biometer", CanonicalName: "Ophthalmic optical biometer"},
	{TargetName: "Biometer", Keywords: []string{"ultrasound", "a scan"}, CommonName: "Ultrasound biometer", CanonicalName: "Ophthalmic ultrasound A-scan biometer"},
	{TargetName: "Biometer", Keywords: []string{}, CommonName: "Ophthalmic biometer", CanonicalName: "Ophthalmic biometer"},
	{TargetName: "Amber screw cap bottle", Keywords: []string{}, CommonName: "Amber bottle", CanonicalName: "Amber glass screw cap bottle"},
	{TargetName: "Bracelet", Keywords: []string{"identification", "patient id"}, CommonName: "Patient ID bracelet", CanonicalName: "Patient identification wristband"},
	{TargetName: "Bracelet", Keywords: []string{}, CommonName: "Medical identification band", CanonicalName: "Hospital patient identification band"},
	{TargetName: "Medicine cabinet", Keywords: []string{"narcotics", "locked"}, CommonName: "Narcotics cabinet", CanonicalName: "Locked narcotics storage cabinet"},
	{TargetName: "Medicine cabinet", Keywords: []string{}, CommonName: "Medicine cabinet", CanonicalName: "Hospital medicine storage cabinet"},
	{TargetName: "Counter", Keywords: []string{"colony"}, CommonName: "Colony counter", CanonicalName: "Microbiology colony counter"},
	{TargetName: "Counter", Keywords: []string{"cell", "blood"}, CommonName: "Cell counter", CanonicalName: "Hematology cell counter"},
	{TargetName: "Counter", Keywords: []string{"gamma"}, CommonName: "Gamma counter", CanonicalName: "Radioimmunoassay gamma counter"},
	{TargetName: "Counter", Keywords: []string{}, CommonName: "Laboratory counter", CanonicalName: "Laboratory counting device"},
	{TargetName: "Defibrillator", Keywords: []string{"automated", "aed", "external automated"}, CommonName: "Automated external defibrillator", CanonicalName: "Automated external defibrillator (AED)"},
	{TargetName: "Defibrillator", Keywords: []string{"manual", "monitor"}, CommonName: "Manual defibrillator monitor", CanonicalName: "Manual defibrillator with physiological monitor"},
	{TargetName: "Defibrillator", Keywords: []string{"implantable", "icd"}, CommonName: "Implantable cardioverter defibrillator", CanonicalName: "Implantable cardioverter defibrillator (ICD)"},
	{TargetName: "Defibrillator", Keywords: []string{}, CommonName: "Defibrillator", CanonicalName: "Emergency cardiac defibrillator"},
}

// OvaholSearchAliasRules holds the legacy Ovahol search aliases as structured data.
var OvaholSearchAliasRules = []SearchAliasRule{
	{Keywords: []string{"electrocardiography", "ecg"}, Aliases: []string{"ECG machine", "EKG machine", "Electrocardiograph"}},
	{Keywords: []string{"electroencephalography", "eeg"}, Aliases: []string{"EEG machine", "EEG accessory"}},
	{Keywords: []string{"ultrasound"}, Aliases: []string{"Ultrasound system", "Sonography system"}},
	{Keywords: []string{"patient monitoring", "patient monitor"}, Aliases: []string{"Vital signs monitor"}},
	{Keywords: []string{"x ray", "radiography"}, Aliases: []string{"Xray machine", "Radiography system"}},
	{Keywords: []string{"endoscope", "endoscopic visualization"}, Aliases: []string{"Endoscope", "Endoscopy system", "Diagnostic scope"}},
	{Keywords: []string{"angiography"}, Aliases: []string{"Cath lab imaging system", "Angio system"}},
	{Keywords: []string{"infusion", "pump"}, Aliases: []string{"IV pump"}},
	{Keywords: []string{"defibrillation", "defibrillator"}, Aliases: []string{"AED"}},
	{Keywords: []string{"dialysis"}, Aliases: []string{"Dialysis unit"}},
	{Keywords: []string{"electrosurgical or radiotherapy energy system"}, Aliases: []string{"Therapeutic energy unit", "Energy therapy system"}},
	{Keywords: []string{"oxygen", "system"}, Aliases: []string{"Oxygen equipment"}},
	{Keywords: []string{"suction", "medical suction"}, Aliases: []string{"Aspirator"}},
	{Keywords: []string{"sterilization", "sterilizer"}, Aliases: []string{"Autoclave"}},
	{Keywords: []string{"clinical information software"}, Aliases: []string{"Clinical system"}},
	{Keywords: []string{"clinical workflow or information software"}, Aliases: []string{"Clinical software", "Health information system"}},
	{Keywords: []string{"imaging or laboratory software"}, Aliases: []string{"Diagnostic system software"}},
	{Keywords: []string{"imaging or laboratory informatics software"}, Aliases: []string{"Diagnostic software", "Imaging software", "Laboratory software"}},
	{Keywords: []string{"rapid diagnostic or point of care test"}, Aliases: []string{"Rapid test", "RDT", "Point-of-care test", "POCT"}},
	{Keywords: []string{"clinical laboratory analyzer"}, Aliases: []string{"Laboratory analyzer", "Lab analyzer"}},
	{Keywords: []string{"general laboratory support"}, Aliases: []string{"Lab equipment", "Lab support equipment"}},
	{Keywords: []string{"laboratory sample preparation and support equipment"}, Aliases: []string{"Sample prep equipment", "Laboratory support equipment"}},
	{Keywords: []string{"in vitro diagnostic reagent or assay kit"}, Aliases: []string{"Diagnostic reagent", "Assay kit"}},
	{Keywords: []string{"biomedical test or calibration analyzer"}, Aliases: []string{"Calibration tester"}},
	{Keywords: []string{"reusable surgical or procedure instrument"}, Aliases: []string{"Surgical tool", "Surgical hand instrument"}},
	{Keywords: []string{"general surgical or interventional instrument"}, Aliases: []string{"Procedure instrument", "Interventional instrument"}},
	{Keywords: []string{"general medical device accessory or disposable"}, Aliases: []string{"Medical consumable", "Device accessory"}},
	{Keywords: []string{"monitoring or neurodiagnostic accessory"}, Aliases: []string{"Monitoring lead", "Electrode accessory"}},
	{Keywords: []string{"dialysis or extracorporeal therapy consumable"}, Aliases: []string{"Dialysis set"}},
	{Keywords: []string{"drainage or thoracic access device"}, Aliases: []string{"Chest drain"}},
	{Keywords: []string{"airway or laryngoscopy accessory"}, Aliases: []string{"Laryngoscope accessory"}},
	{Keywords: []string{"laboratory biosafety cabinet or fume hood"}, Aliases: []string{"Biosafety cabinet", "Fume hood"}},
	{Keywords: []string{"laboratory thermal control or cold storage device"}, Aliases: []string{"Lab freezer", "Lab bath"}},
	{Keywords: []string{"cardiac pacing or circulatory support system"}, Aliases: []string{"Pacemaker system", "Circulatory support device"}},
	{Keywords: []string{"patient warming or cooling therapy system"}, Aliases: []string{"Patient warmer", "Cooling therapy device"}},
	{Keywords: []string{"general therapeutic or life support equipment"}, Aliases: []string{"Therapeutic device", "Life-support equipment"}},
	{Keywords: []string{"neonatal therapy or support system"}, Aliases: []string{"Neonatal support unit"}},
	{Keywords: []string{"compression immobilization or support therapy device"}, Aliases: []string{"Compression therapy device"}},
	{Keywords: []string{"ophthalmic therapeutic or procedure system"}, Aliases: []string{"Ophthalmic treatment system"}},
	{Keywords: []string{"ophthalmic diagnostic imaging system"}, Aliases: []string{"OCT machine"}},
	{Keywords: []string{"assistive communication or cognitive support device"}, Aliases: []string{"Communication aid"}},
	{Keywords: []string{"vision or hearing assistive aid"}, Aliases: []string{"Sensory aid"}},
	{Keywords: []string{"assistive vision or hearing product"}, Aliases: []string{"Sensory aid", "Assistive sensory product"}},
	{Keywords: []string{"orthotic prosthetic or support aid"}, Aliases: []string{"Orthotic aid", "Prosthetic aid"}},
	{Keywords: []string{"assistive daily living or self care aid"}, Aliases: []string{"Daily living aid"}},
	{Keywords: []string{"pressure relief or positioning aid"}, Aliases: []string{"Positioning aid"}},
	{Keywords: []string{"environmental accessibility or support aid"}, Aliases: []string{"Accessibility aid"}},
	{Keywords: []string{"clinical chart", "record form", "register"}, Aliases: []string{"Growth chart", "Clinical form"}},
	{Keywords: []string{"administrative or general facility support equipment"}, Aliases: []string{"Support equipment", "General support equipment"}},
	{Keywords: []string{"protective apron barrier or shield"}, Aliases: []string{"Radiation apron", "Protective shield"}},
	{Keywords: []string{"radiation or barrier protection apron or shield"}, Aliases: []string{"Protective apron", "Barrier protection"}},
	{Keywords: []string{"respiratory or anesthesia mask interface"}, Aliases: []string{"Anesthesia mask", "Respiratory mask"}},
	{Keywords: []string{"breathing circuit or ventilator accessory"}, Aliases: []string{"Breathing circuit", "Ventilator accessory"}},
	{Keywords: []string{"airway or breathing circuit consumable"}, Aliases: []string{"Airway accessory"}},
	{Keywords: []string{"airway gas monitoring or absorber accessory"}, Aliases: []string{"CO2 detector", "CO2 absorber"}},
	{Keywords: []string{"medical gas outlet cylinder or supply item"}, Aliases: []string{"Medical gas supply"}},
	{Keywords: []string{"surgical drape or sterile cover"}, Aliases: []string{"Sterile drape"}},
	{Keywords: []string{"general facility utility or support asset"}, Aliases: []string{"Facility support equipment"}},
	{Keywords: []string{"hospital furniture or bedside fixture"}, Aliases: []string{"Hospital furniture", "Medical furniture"}},
	{Keywords: []string{"ambulance or field support vehicle"}, Aliases: []string{"Transport vehicle", "Ambulance"}},
	{Keywords: []string{"administrative it or general operations support equipment"}, Aliases: []string{"Administrative support equipment", "Support equipment"}},
}

// OvaholTypeByKeyword holds the Ovahol keyword-to-type rules.
var OvaholTypeByKeyword = []struct {
	Keywords []string `json:"keywords"`
	Type     string   `json:"type"`
}{
	{Keywords: []string{"software", "pacs", "electronic medical record", "emr", "ehr", "clinical information system"}, Type: "DIGITAL_HEALTH_CLINICAL_SOFTWARE"},
	{Keywords: []string{"calibration", "quality control", "testing system", "tester", "test equipment", "patient simulator", "simulator", "phantom", "electrical safety"}, Type: "BIOMEDICAL_TEST_CALIBRATION_QUALITY_ASSURANCE"},
	{Keywords: []string{"ultrasound", "x ray", "xray", "ct ", "computed tomography", "mri", "magnetic resonance", "fluoroscopy", "mammograph", "radiograph", "nuclear medicine", "gamma camera", "endoscope", "bronchoscope", "cystoscope", "colposcope", "laparoscope", "arthroscope", "otoscope", "ophthalmoscope"}, Type: "DIAGNOSTIC_IMAGING_VISUALIZATION"},
	{Keywords: []string{"ivd", "reagent", "assay", "hematology", "chemistry analyzer", "chemistry analyser", "centrifuge", "microscope", "pcr", "blood gas", "laboratory", "specimen", "sample"}, Type: "LABORATORY_IN_VITRO_DIAGNOSTICS"},
	{Keywords: []string{"oxygen", "suction", "airway", "nebul", "flowmeter", "humidifier", "psa", "breathing circuit", "respiratory", "cpap", "bipap", "aspirator"}, Type: "MEDICAL_GAS_RESPIRATORY_SUCTION"},
	{Keywords: []string{"ventilator", "infusion", "syringe pump", "defibrillator", "dialysis", "anaesthesia", "anesthesia", "electrosurgical", "pacemaker", "cardioverter", "apheresis", "resuscitator", "life support"}, Type: "THERAPEUTIC_LIFE_SUPPORT"},
	{Keywords: []string{"monitor", "ecg", "eeg", "tonometer", "audiometer", "spirom", "pulmonary function", "bilirubinometer", "vital signs", "blood pressure", "stethoscope"}, Type: "CLINICAL_MONITORING_ASSESSMENT"},
	{Keywords: []string{"wheelchair", "walker", "crutch", "prosthe", "ortho", "mobility", "assistive", "rehabilitation", "physiotherapy"}, Type: "REHABILITATION_MOBILITY_ASSISTIVE"},
	{Keywords: []string{"steriliz", "autoclave", "disinfect", "decontamin", "ipc", "glove", "mask", "gown", "apron"}, Type: "INFECTION_PREVENTION_DECONTAMINATION_STERILIZATION"},
	{Keywords: []string{"surgical", "instrument", "tray", "trocar", "catheter", "cannula", "implant", "clip", "stent", "laparoscopy", "dental", "oral", "iud", "intra uterine", "intra uterine system", "anoscope", "scope sheath"}, Type: "SURGICAL_INTERVENTIONAL"},
	{Keywords: []string{"dressing", "gauze", "bandage", "pad", "syringe", "needle", "tube", "drainage", "bag", "collection", "accessory", "swab", "suture", "condom", "diaphragm", "cervical cap"}, Type: "CONSUMABLES_ACCESSORIES_PROCEDURE_SUPPLIES"},
	{Keywords: []string{"bed", "cabinet", "ambulance", "vehicle", "chart", "stationery", "waste", "clock", "printer", "data logger", "lamp", "radiation shielding", "shielding"}, Type: "FACILITY_UTILITY_ENVIRONMENTAL_SUPPORT"},
}

// OvaholSourceTypeMap maps source device types to canonical Ovahol types.
var OvaholSourceTypeMap = map[string]string{
	"medical equipment":              "Treatment, Surgical & Life Support Devices",
	"accessories":                    "Consumables & Accessories",
	"collection devices":             "Consumables & Accessories",
	"catheters and related":          "Consumables & Accessories",
	"contraception devices":          "Consumables & Accessories",
	"endoscopes and related devices": "Diagnostic & Imaging Devices",
	"implantable devices":            "Treatment, Surgical & Life Support Devices",
	"measurement devices":            "Monitoring & Measurement Devices",
	"non medical devices":            "Support Equipment & Furniture",
	"oral devices":                   "Treatment, Surgical & Life Support Devices",
	"personal protective equipment radiation protection equipment": "Sterilization & Infection Control Devices",
	"solutions and reagents":                                "Laboratory & IVD Equipment",
	"consumables for medical equipment":                     "Consumables & Accessories",
	"laboratory equipment":                                  "Laboratory & IVD Equipment",
	"medical furniture":                                     "Support Equipment & Furniture",
	"medical gas equipment":                                 "Medical Gas & Respiratory Devices",
	"monitoring equipment":                                  "Monitoring & Measurement Devices",
	"quality assurance / calibration / maintenance devices": "Laboratory & IVD Equipment",
	"radiotherapy-related equipment":                        "Treatment, Surgical & Life Support Devices",
	"rehabilitation devices":                                "Treatment, Surgical & Life Support Devices",
	"respiratory accessories":                               "Medical Gas & Respiratory Devices",
	"simulators / trainers":                                 "Support Equipment & Furniture",
	"software":                                              "Clinical / Facility Software",
	"surgical instruments, trays and bowls":                 "Treatment, Surgical & Life Support Devices",
	"sutures":                                               "Consumables & Accessories",
	"syringes and needles":                                  "Consumables & Accessories",
	"tubes and cannulae":                                    "Consumables & Accessories",
	"waste management products":                             "Support Equipment & Furniture",
	"assistive products":                                    "Treatment, Surgical & Life Support Devices",
	"cleaning / disinfection / sterilization equipment":     "Sterilization & Infection Control Devices",
	"cleaning / disinfection / sterilization solutions":     "Sterilization & Infection Control Devices",
	"dressings, gauzes, bandages, pads":                     "Consumables & Accessories",
	"imaging / nuclear medicine equipment":                  "Diagnostic & Imaging Devices",
	"in vitro diagnostic tests":                             "Laboratory & IVD Equipment",
	"infection prevention and control (ipc)":                "Sterilization & Infection Control Devices",
	"infusion devices":                                      "Treatment, Surgical & Life Support Devices",
}

// DefaultTaxonomy returns the default Ovahol taxonomy instance for backwards compatibility.
func DefaultTaxonomy() *Taxonomy {
	genericHeads := make([]string, 0, len(GenericLegacyHeads))
	for h := range GenericLegacyHeads {
		genericHeads = append(genericHeads, h)
	}
	legacyDesc := make([]string, 0, len(LegacyDescriptorPhrases))
	for p := range LegacyDescriptorPhrases {
		legacyDesc = append(legacyDesc, p)
	}

	typeDefaultsMap := make(map[string]struct {
		Function string `json:"function"`
		Risk     string `json:"risk"`
	}, len(DeviceTypeDefaults))
	for k, v := range DeviceTypeDefaults {
		typeDefaultsMap[k] = struct {
			Function string `json:"function"`
			Risk     string `json:"risk"`
		}{
			Function: v.Function,
			Risk:     v.Risk,
		}
	}

	return &Taxonomy{
		ID:                     "ovahol-ontology",
		Name:                   "Ovahol Medical Device Taxonomy",
		Version:                "1.0.0",
		SchemaVersion:          "1.0.0",
		DeviceTypes:            DeviceTypes,
		DeviceCategories:       DeviceCategories,
		DeviceFunctions:        DeviceFunctions,
		DeviceApplicationRisks: DeviceApplicationRisks,
		NamingRules:            NamingRules,
		Inference: &InferenceRules{
			TypeByCode:              TypeByCode,
			TypeByKeyword:           OvaholTypeByKeyword,
			SourceTypeMap:           OvaholSourceTypeMap,
			SupportedSourceTypes:    SupportedSourceTypes,
			FamilyRules:             FamilyRules,
			SpecificNameRules:       SpecificNameRules,
			TypeDefaults:            typeDefaultsMap,
			GenericLegacyHeads:      genericHeads,
			LegacyDescriptorPhrases: legacyDesc,
			NameRefinementRules:     OvaholNameRefinementRules,
			SearchAliasRules:        OvaholSearchAliasRules,
			Acronyms:                []string{"ecg", "ekg", "eeg", "emg", "mri", "ct", "pcr", "ivd", "aed", "cpr", "iv", "iud", "cpap", "bipap", "psa", "hba1c", "spo2", "nibp", "ibp", "tcd", "emr", "ehr", "pacs", "lis", "his", "ris", "ipc", "ppe", "uv", "led", "tcare", "av", "rf", "dc", "ac", "dsa", "pet", "spect", "oct", "tace", "icp", "eeg/ep", "eswl"},
			WordReplacements: map[string]string{
				"anaesthesia": "anesthesia",
				"analyser":    "analyzer",
				"centrifug":   "centrifuge",
				"haem":        "hem",
				"orthopaedic": "orthopedic",
				"paediatric":  "pediatric",
			},
		},
	}
}
